### PR TITLE
Add test for User

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@MGatner It currently got the following error: 

```bash
There was 1 failure:1) UserTest::testShowsOwnFiles
Failed asserting that false is true./Users/samsonasik/www/codeigniter4-files/tests/controller/UserTest.php:19
```

any suggestion?

**Comment by MGatner** [comment]
You need to assign the file to the user. E.g.
`model('FileModel')->addToUser($file->id, $user->id)`

See also `FilesTestCase::createUserWithFiles()`

**Comment by samsonasik** [comment]
@MGatner Thank you, it fixed now.

**Comment by samsonasik** [comment]
implemented: 

~ UserTest.php

- [x] testShowsOwnFiles
- [x]  testShowsOtherFiles

**Comment by MGatner** [comment]
Is this ready to merge? Or are you planning to add more to it?

**Comment by samsonasik** [comment]
it is ready, if you think it need more check, just let me know

**Comment by MGatner** [comment]
I think this is good for now. We will need to get into permissions but that might be its own suite.

**Pull request merged**
